myShop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls', namespace='products')),
    path('register/', user_views.register,name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('profile/', user_views.profile,name='profile'),
    path('tech/', user_views.tech,name='tech'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myShop/products/urls.py
from django.urls import path
from .views import (
    about,
    checkout,
    contact,
    search,
    query,
    placed,
    index,
    ProductDetailView,
    add_to_cart,
    viewcart,
    removeitem,
    updatecart
)

app_name = 'products'

urlpatterns = [
    path('', index, name='home'),
    path('product/<pk>/', ProductDetailView.as_view(), name='product'),
    path('about/', about, name='about'),
    path('search/', search, name='search'),
    path('contact-us/', contact, name='contact-us'),
    path('query/', query, name='query'),
    path('checkout/', checkout, name='checkout'),
    path('order-placed/', placed, name='order-placed'),
    path('add-to-cart/<int:phoneId>/', add_to_cart, name='add-to-cart'),
    path("viewcart", viewcart, name="viewcart"),
    path('remove-from-cart/<int:pk>/', removeitem, name='remove-from-cart'),
    path("updatecart", updatecart, name="updatecart"),
]

myShop/templates/base.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>SmartHome</title>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  
  <style>
    .page-footer {
    background-color: #929fba;
    }
  </style>

</head>
<body>
  <div class="d-flex flex-column min-vh-100">
    <header class="site-header">
      <!-- Navbar -->
      <nav class="navbar  navbar-expand-sm navbar-light bg-primary">
        <div class="container">
          <!-- Brand -->
          <a class="navbar-brand custom" href="/">
            <strong class="white-text">SmartHome</strong>
          </a>

          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:contact-us' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'tech' %}">Technologies
                    <span class="badge badge-pill danger-color">new</span>
                  </a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:contact-us' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'tech' %}">Technologies
                    <span class="badge badge-pill danger-color">new</span>
                  </a>
                </li>
              {% endif %}
            </div>

            <!-- Right -->
            <div class="navbar-nav nav-flex-icons">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'products:viewcart' %}" class="nav-link waves-effect">
                    <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_product_count }} </span>
                    <i class="fas fa-shopping-cart"></i>
                    <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="/logout">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'register' %}">Register</a>
                </li>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    <!-- Navbar -->
    </header>
    <main class="flex-fill">
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </main>
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      <hr class="my-4">
      <!-- Social icons -->
      <div class="pb-4">
        <a href="" target="_blank">
          <i class="fab fa-facebook-f mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-twitter mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-youtube mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-google-plus-g mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-dribbble mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-pinterest mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-github mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-codepen mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->

      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2021   Copyright:
        <a href="/"> SmartHome.com </a>
      </div>
      <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
  </div>

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>
</html>