myShop/myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls', namespace='products')),
    path('register/', user_views.register,name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('password-reset/done',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
    path('profile/', user_views.profile,name='profile'),
    path('tech/', user_views.tech,name='tech'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myShop/products/urls.py
from django.urls import path
from .views import (
    about,
    checkout,
    contact,
    search,
    query,
    placed,
    index,
    ProductDetailView,
    add_to_cart,
    viewcart,
    removeitem,
    updatecart
)

app_name = 'products'

urlpatterns = [
    path('', index, name='home'),
    path('product/<pk>/', ProductDetailView.as_view(), name='product'),
    path('about/', about, name='about'),
    path('search/', search, name='search'),
    path('contact-us/', contact, name='contact-us'),
    path('query/', query, name='query'),
    path('checkout/', checkout, name='checkout'),
    path('order-placed/', placed, name='order-placed'),
    path('add-to-cart/<int:phoneId>/', add_to_cart, name='add-to-cart'),
    path("viewcart", viewcart, name="viewcart"),
    path('remove-from-cart/<int:pk>/', removeitem, name='remove-from-cart'),
    path("updatecart", updatecart, name="updatecart"),
]

myShop/products/models.py
from django.db import models
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=20)

    @staticmethod
    def get_all_categories():
        return Category.objects.all()

    def __str__(self):
        return self.name


class Phone(models.Model):
    phoneId = models.AutoField(primary_key=True)
    phoneName = models.CharField(max_length=255)
    phonePrice = models.FloatField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    phoneDescription = models.TextField()
    image_url = models.CharField(max_length=2083)

    @staticmethod
    def get_all_products_by_categoryid(category_id):
        if category_id:
            return Phone.objects.filter(category = category_id)
        else:
            return Phone.objects.all()


    def __str__(self):
        return self.phoneName



class CartItem(models.Model):
    phone = models.ForeignKey(Phone,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.phone.phoneName} - {self.quantity}"

    def get_total_item_price(self):
        return self.quantity * self.phone.phonePrice


class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    itemlist = models.ManyToManyField(CartItem)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} {self.itemlist.all()}"

    def __repr__(self) -> str:
        return f"{self.user.username} {len(self.itemlist.all())}"

    def get_total(self):
        total = 0
        for item in self.itemlist.all():
            total += item.get_total_item_price()
        return total

myShop/products/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import redirect
from django.core.paginator import Paginator
from .models import Phone, CartItem, Cart, Category


def index(req):
    page_obj = None
    categories = Category.get_all_categories()
    categoryId = req.GET.get('category')
    if categoryId:
        page_obj = Phone.get_all_products_by_categoryid(categoryId)
    else:
        products = Phone.objects.all()
        paginator = Paginator(products, 6)
        page_number = req.GET.get('page')
        page_obj = paginator.get_page(page_number)
    data = {}
    data['page_obj'] = page_obj
    data['categories'] = categories
    return render(req, 'home.html', data)


def about(req):
    return render(req, 'about.html')


class ProductDetailView(DetailView):
    model = Phone
    template_name = 'product.html'


def about(req):
    return render(req, 'about.html')


def contact(req):
    return render(req, 'contact.html')


def checkout(req):
    return render(req, 'checkout-page.html')


def search(req):
    query = req.GET['query']
    product = Phone.objects.filter(phoneName__icontains=query)
    context = {'product': product, 'query': query}
    return render(req, 'search.html', context)


def query(req):
    return render(req, 'query.html')


def placed(req):
    return render(req, 'placed.html')


@login_required
def add_to_cart(req, phoneId):
    cart, status = Cart.objects.get_or_create(user=req.user)
    phone = Phone.objects.get(phoneId=phoneId)
    item, created = CartItem.objects.get_or_create(phone=phone)
    if cart.itemlist.filter(id=item.id).exists():
        item.quantity = item.quantity + 1
        item.save()
        messages.info(req, 'This product quantity was updated')
        return redirect("products:viewcart")
    else:
        cart.itemlist.add(item)
        messages.info(req, 'This product was added to your cart')
        return redirect("products:viewcart")


@login_required
def viewcart(req):
    cart, status = Cart.objects.get_or_create(user=req.user)
    context = {'cart': cart}
    return render(req, 'viewcart.html', context)


@login_required
def removeitem(req, pk):
    item = CartItem.objects.get(pk=pk)
    item.delete()
    messages.success(req, f"{item.phone.phoneName} is remove from Cart")
    return redirect("products:viewcart")


@login_required
def updatecart(req):
    id = int(req.GET['id'])
    quantity = int(req.GET['quantity'])
    item = CartItem.objects.filter(pk=id)
    item.update(quantity=quantity)
    return HttpResponse(f"{item[0].phone.phoneName} is updated with {item[0].quantity} Quantity...")

myShop/products/templates/checkout-page.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <div class="container wow fadeIn">
      <h2 class="my-3 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form class="card-body">
              <div class="md-form mb-5">
                <input type="text" id="address" class="form-control" placeholder="Valid Address">
                <label for="address" class="">Address</label>
              </div>
              <div class="md-form mb-5">
                <input type="text" id="address-2" class="form-control" placeholder="Alternate Address">
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>
              <div class="md-form mb-5">
                <input type="text" id="phone number" class="form-control" placeholder="Valid Phone Number">
                <label for="phone number" class="">Phone Number</label>
              </div>
              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>India</option>
                  </select>
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="state">State</label>
                  <select class="custom-select d-block w-100" id="state" required>
                    <option value="">Choose...</option>
                    <option>Maharashtra</option>
                    <option>Goa</option>
                    <option>West Bengal</option>
                    <option>Punjab</option>
                    <option>Kerala</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="zip">Zip</label>
                  <input type="text" class="form-control" id="zip" placeholder="" required>
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>
              <hr class="mb-4">
              <a class='btn btn-primary float-none' href="{% url 'products:order-placed' %}">
                Continue to checkout
              </a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

myShop/products/templates/home.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>SmartHome</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  
  <style>
    .page-footer {
    background-color: #929fba;
    }
  </style>
</head>
<body>

    <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container">
          <!-- Brand -->
          <a class="navbar-brand custom" href="/">
            <strong class="white-text">SmartHome</strong>
          </a>

          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:contact-us' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'tech' %}">Technologies
                    <span class="badge badge-pill danger-color">new</span>
                  </a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:contact-us' %}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'tech' %}">Technologies
                    <span class="badge badge-pill danger-color">new</span>
                  </a>
                </li>
              {% endif %}
            </div>

            <!-- Right -->
            <div class="navbar-nav nav-flex-icons">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'products:viewcart' %}" class="nav-link waves-effect">
                    <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_product_count }} </span>
                    <i class="fas fa-shopping-cart"></i>
                    <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="/logout">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'register' %}">Register</a>
                </li>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    <!-- Navbar -->

    <!--Carousel Wrapper-->
    <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
      <!--Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-1z" data-slide-to="1"></li>
        <li data-target="#carousel-example-1z" data-slide-to="2"></li>
      </ol>
      <!--/.Indicators-->
      <!--Slides-->
      <div class="carousel-inner" role="listbox">
        <!--First slide-->
        <div class="carousel-item active">
          <img class="container-fluid" src="/media/banner3.jpg"
            alt="First slide">
        </div>
        <!--/First slide-->
        <!--Second slide-->
        <div class="carousel-item">
          <img class="container-fluid" src="/media/banner1.jpg"
            alt="Second slide">
        </div>
        <!--/Second slide-->
        <!--Third slide-->
        <div class="carousel-item">
          <img class="container-fluid" src="/media/banner2.jpg"
            alt="Third slide">
        </div>
        <!--/Third slide-->
      </div>
      <!--/.Slides-->
      <!--Controls-->
      <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      <!--/.Controls-->
    </div>
    <!--/.Carousel Wrapper-->

    <main>
      <div class="container">
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand custom">
          <strong class="red-text">Brands:</strong>
        </span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for category in categories %}
            <li class="nav-item">
              <a class="nav-link" href="/?category={{category.id}}">{{category.name}}</a>
            </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form method="get" action="/search" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
        <!-- Collapsible content -->

        </nav>
        <!--/.Navbar-->


        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <h1>
          <p class="text-center font-weight-bold text-primary ">
            Avaiable Products
          </p>
        </h1>

        <div class="col-lg-13 mx-auto">
          <div class="row mx-auto">
            {% for product in page_obj %}
            <div class="card mx-auto mb-5" style="width: 18rem;">
                 <img src="{{ product.image_url }}" class="card-img-top" alt="...">
                     <div class="card-body">
                         <h5 class="card-title">{{ product.phoneName }}</h5>
                         <p class="card-text"> {{ product.phonePrice }} ₹ </p>
                         <a href="/product/{{product.phoneId}}/" class="btn btn-info">More Details</a>
                     </div>
            </div>
            {% endfor %}
          </div>
        </div>
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
      </div>
    </main>
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      <hr class="my-4">
      <!-- Social icons -->
      <div class="pb-4">
        <a href="" target="_blank">
          <i class="fab fa-facebook-f mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-twitter mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-youtube mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-google-plus-g mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-dribbble mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-pinterest mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-github mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-codepen mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->

      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2021   Copyright:
        <a href="/"> SmartHome.com </a>
      </div>
      <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
  </div>

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>
</html>

myShop/products/templates/placed.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>SmartHome</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'products/main.css' %}">

  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 0vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>
<body>
  <div class="d-flex flex-column min-vh-100">
    <header class="site-header">
      <!-- Navbar -->
      <nav class="navbar fixed-top navbar-expand-sm navbar-light bg-primary scrolling-navbar">
        <div class="container">
          <!-- Brand -->
          <a class="navbar-brand custom" href="/">
            <strong class="white-text">SmartHome</strong>
          </a>

          <!-- Collapse -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Links -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <div class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:contact-us' %}">Contact Us</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:about' %}">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'products:contact-us' %}">Contact Us</a>
                </li>
              {% endif %}
            </div>

            <!-- Right -->
            <div class="navbar-nav nav-flex-icons">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="/logout">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link waves-effect" href="{% url 'register' %}">Register</a>
                </li>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    <!-- Navbar -->
    </header>
    <main class="flex-fill">
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="container">
        <h1>
            <p class="text-center font-weight-bold text-info">
                Thank You!
            </p>
        </h1>
        <h2>
            <p class="text-center text-success">
                Your order has been placed successfully
            </p>
        </h2>
        <h4>
            <p class="text-center text-secondary">
               Your Username: {{ user.username }}
            </p>
            <p class="text-center text-secondary">
               Your Email: {{ user.email }}
            </p>
            <p class="text-center text-danger">
               Payment Mod: COD
            </p>
        </h4>
        <h3>
            <p class="text-center text-warning font-weight-bold">
                Your order will be delivered in next 24 hours at your doorstep
            </p>
        </h3>
        </div>
      </div>
    </main>
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      <hr class="my-4">
      <!-- Social icons -->
      <div class="pb-4">
        <a href="" target="_blank">
          <i class="fab fa-facebook-f mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-twitter mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-youtube mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-google-plus-g mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-dribbble mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-pinterest mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-github mr-3"></i>
        </a>
        <a href="" target="_blank">
          <i class="fab fa-codepen mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->

      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2021   Copyright:
        <a href="/"> SmartHome.com </a>
      </div>
      <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
  </div>

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>
</html>

myShop/products/templates/query.html
{% extends 'base.html' %}
{% block content %}
    <h2>
        <p class="text-center font-weight-bold text-info">
            Your query has been submitted successfully.We will contact you as soon as possible.
        </p>
        <p class="text-center font-weight-bold text-info">
            Thank You!
        </p>
    </h2>
{% endblock %}

myShop/products/templates/viewcart.html
{% extends "base.html" %}
{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(function(){
        $("input[name='quantity']").change(function(){
            let id = $(this).attr("id")
            let quantity = $(this).val()

            //Ajay GET request
            $.get("updatecart",{"id":id,"quantity":quantity},function(data,status){
                alert(data)
            }) 
        })
    })
</script>

    <div class="table-responsive text-nowrap">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Product Price</th>
          </tr>
        </thead>
        <tbody>
        {% for item in cart.itemlist.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ item.phone.phoneName }}</td>
            <td>{{ item.phone.phonePrice }} ₹</td>
            <th><input style="width:80px;" class="form-control" type="number" min="1" value="{{item.quantity}}" id="{{item.pk}}" name="quantity"/></th>            

            <td>{{ item.get_total_item_price }} ₹
              <a style="color: red;" href="/remove-from-cart/{{item.pk}}">
                <i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
        {% empty %}
        <tr>
          <td colspan="5">Your cart is empty</td>
        </tr>
        <tr>
          <td colspan="5">
            <a class="btn btn-primary float-right" href="/">Continue Shoping</a>
          </td>
        </tr>
        {% endfor %}
        {% if cart.get_total %}
        <tr>
          <td colspan="4"><b>Order Total</b></td>
          <td><b>{{ cart.get_total }} ₹</b></td>
        </tr>
        <tr>
          <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href="{% url 'products:checkout' %}">Proceed to checkout</a>
            <a class='btn btn-primary float-right' href="{% url 'products:home' %}">Continue shopping</a>
          </td>

        </tr>
        {% endif %}
        </tbody>
      </table>
    </div>
{% endblock %}